# Generated by Django 2.2.7 on 2019-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='perfil',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
