# Generated by Django 2.2.7 on 2019-11-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191127_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'candidato'), (2, 'empresa')]),
        ),
    ]
